Repository green-ecolution/green-ecolution-frontend, pull requests merged in 2025-02, with the labels that each got.

#373 Fix/update user values
  frontend/src/components/general/cards/SelectedCard.tsx
  frontend/src/components/general/cards/SelectedClusterCard.tsx
  frontend/src/components/general/cards/SensorCard.tsx
  frontend/src/components/general/cards/TreeCard.tsx
  frontend/src/components/general/cards/TreeclusterCard.tsx
  frontend/src/components/general/cards/UserCard.tsx
  frontend/src/components/general/cards/VehicleCard.tsx
  frontend/src/components/general/cards/WateringPlanCard.tsx
  frontend/src/components/general/filter/fieldsets/StatusFieldset.tsx
  frontend/src/components/general/form/FormForTreecluster.tsx
  frontend/src/components/general/form/FormForVehicle.tsx
  frontend/src/components/map/marker/ClusterMarker.tsx
  frontend/src/components/map/marker/TreeMarker.tsx
  frontend/src/components/sensor/SensorDashboard.tsx
  frontend/src/components/tree/TabSensorData.tsx
  frontend/src/components/tree/TabWateringStatus.tsx
  frontend/src/components/treecluster/TreeClusterDashboard.tsx
  frontend/src/components/vehicle/VehicleDashboard.tsx
  frontend/src/components/watering-plan/TabGeneralData.tsx
  frontend/src/components/watering-plan/WateringPlanDashboard.tsx
  frontend/src/components/watering-plan/WateringPlanStatusUpdate.tsx
  frontend/src/components/watering-plan/WateringPlanUpdate.tsx
  frontend/src/hooks/details/useDetailsForDrivingLicense.ts
  frontend/src/hooks/details/useDetailsForSensorStatus.ts
  frontend/src/hooks/details/useDetailsForSoilCondition.ts
  frontend/src/hooks/details/useDetailsForUserRole.ts
  frontend/src/hooks/details/useDetailsForUserStatus.ts
  frontend/src/hooks/details/useDetailsForVehicleStatus.ts
  frontend/src/hooks/details/useDetailsForVehicleType.ts
  frontend/src/hooks/details/useDetailsForWateringPlanStatus.ts
  frontend/src/hooks/details/useDetailsForWateringStatus.ts
  frontend/src/hooks/useDetailsForDrivingLicense.ts
  frontend/src/hooks/useDetailsForUser.ts
  frontend/src/hooks/useFilter.ts
  frontend/src/lib/types/keycloak.ts
  frontend/src/routes/_protected/map/index.tsx
  frontend/src/routes/_protected/profile.tsx
  frontend/src/routes/_protected/team/index.tsx
  frontend/src/routes/_protected/treecluster/index.tsx
  frontend/src/store/user/types.ts
  frontend/src/store/user/userStore.ts
Labels: need-reviewer

#381 feat: add pagination component to treecluster
  frontend/src/api/queries.ts
  frontend/src/components/general/Pagination.tsx
  frontend/src/components/general/links/PaginationLink.tsx
  frontend/src/routes/_protected/treecluster/index.tsx
Labels: need-reviewer

#388 feat: add pagination to watering plan list
  frontend/src/api/queries.ts
  frontend/src/routes/_protected/watering-plans/index.tsx
Labels: need-reviewer

#386 feat: add pagination for sensors
  frontend/src/api/queries.ts
  frontend/src/routes/_protected/sensors/index.tsx
Labels: need-reviewer

#389 feat: add pagination to vehicle list
  frontend/src/api/queries.ts
  frontend/src/routes/_protected/vehicles/index.tsx
Labels: need-reviewer

#391 Feature/add list view for trees
  frontend/src/api/queries.ts
  frontend/src/components/general/cards/TreeCard.tsx
  frontend/src/components/layout/Navigation.tsx
  frontend/src/components/sensor/SensorDashboard.tsx
  frontend/src/components/tree/TreeDashboard.tsx
  frontend/src/components/tree/TreeUpdate.tsx
  frontend/src/components/treecluster/TreeClusterDashboard.tsx
  frontend/src/components/watering-plan/WateringPlanRoutePreview.tsx
  frontend/src/hooks/form/useTreeForm.ts
  frontend/src/routeTree.gen.ts
  frontend/src/routes/_protected/debug.tsx
  frontend/src/routes/_protected/map/index.tsx
  frontend/src/routes/_protected/map/tree/edit.tsx
  frontend/src/routes/_protected/map/tree/new.tsx
  frontend/src/routes/_protected/tree/$treeId.tsx
  frontend/src/routes/_protected/trees/$treeId.tsx
  frontend/src/routes/_protected/trees/_formular.tsx
  frontend/src/routes/_protected/trees/_formular/$treeId.edit.tsx
  frontend/src/routes/_protected/trees/_formular/$treeId.tsx
  frontend/src/routes/_protected/trees/_formular/new.tsx
  frontend/src/routes/_protected/trees/index.tsx
Labels: need-reviewer

#403 Bugfix/do not show empty treecluster
  frontend/src/components/general/cards/TreeclusterCard.tsx
  frontend/src/components/map/marker/WithAllClusters.tsx
Labels: need-reviewer

#405 feat: expand watering status with value »just watered«
  frontend/src/components/general/cards/EntitiesStatusCard.tsx
  frontend/src/components/tree/TabGeneralData.tsx
  frontend/src/components/tree/TabWateringStatus.tsx
  frontend/src/components/tree/TreeDashboard.tsx
  frontend/src/hooks/details/useDetailsForWateringStatus.ts
  frontend/tailwind.config.ts
Labels: need-reviewer

#414 fix: URL is incorrect if trying to open "deep" sites
  frontend/src/routes/_protected.tsx
Labels: bug, need-reviewer

#419 fix: show origin of tree
  frontend/src/components/tree/TabGeneralData.tsx
  frontend/src/components/tree/TreeDashboard.tsx
  frontend/src/components/tree/TreeUpdate.tsx
  frontend/src/routes/_protected/trees/_formular/new.tsx
  frontend/src/schema/treeSchema.ts
Labels: need-reviewer

#402 fix: update content on startpage
  frontend/src/components/startpage/IntroductionSlider.tsx
  frontend/src/components/startpage/KeyFacts.tsx
  frontend/src/components/startpage/QuickLinks.tsx
  frontend/src/css/components/splide.css
  frontend/src/routes/index.tsx
Labels: need-reviewer

#421 Update Backend API Client
  backend-client/package.json
  frontend/src/components/tree/TreeUpdate.tsx
  frontend/src/routes/_protected/trees/_formular/new.tsx
  frontend/src/schema/treeSchema.ts
Labels: need-reviewer

#406 feat: add graphs for watering status values and sensor values
  frontend/package.json
  frontend/src/api/queries.ts
  frontend/src/components/tree/ChartSensorData.tsx
  frontend/src/components/tree/ChartWateringData.tsx
  frontend/src/components/tree/TabSensorData.tsx
  frontend/src/components/tree/TabWateringStatus.tsx
  yarn.lock
Labels: need-reviewer

#408 Feature/wateringplan evaluation
  frontend/src/components/general/cards/SelectedCard.tsx
  frontend/src/components/general/cards/SelectedClusterCard.tsx
  frontend/src/components/general/form/types/Input.tsx
  frontend/src/components/watering-plan/TabGeneralData.tsx
  frontend/src/components/watering-plan/WateringPlanStatusUpdate.tsx
  frontend/src/routes/_protected/trees/index.tsx
  frontend/src/schema/wateringPlanSchema.ts
Labels: need-reviewer

#423 Feature/Hide filter when not on map
  frontend/src/routes/_protected/trees/index.tsx
Labels: need-reviewer

#431 fix: show correct tree card values, fix spelling mistake
  frontend/src/components/general/cards/TreeCard.tsx
  frontend/src/components/tree/TabSensorData.tsx
  frontend/src/components/treecluster/TreeClusterDashboard.tsx
Labels: need-reviewer

#441 fix: changed vehicle minimum water to 120
  frontend/src/routes/_protected/vehicles/_formular/new.tsx
  frontend/src/schema/vehicleSchema.ts
Labels: need-reviewer

#434 fix: forbid DrivingLicense Unknown
  frontend/src/hooks/details/useDetailsForDrivingLicense.ts
  frontend/src/routes/_protected/vehicles/_formular/new.tsx
  frontend/src/schema/vehicleSchema.ts
Labels: need-reviewer

#440 fix: archive vehicles instead of deleting them
  frontend/src/components/treecluster/DeleteSection.tsx
  frontend/src/components/vehicle/VehicleUpdate.tsx
  frontend/src/components/watering-plan/TabGeneralData.tsx
Labels: need-reviewer

#446 fix: render issue in tree markers
  frontend/src/components/map/marker/MarkerList.tsx
Labels: bug
